server.port=8082
spring.application.name=cart-service

spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=cartdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=StrongPassw0rd!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic.cart=cart-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer